[env:heltec_wifi_lora_32_v3]
platform = espressif32
board = heltec_wifi_lora_32_v3
framework = arduino
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5

lib_deps =
    jgromes/RadioLib
    adafruit/Adafruit BMP085 Library
    sensirion/Sensirion I2C SCD4x
