[env:heltec_wifi_lora_32_v3]
platform = espressif32@6.8.1
board = heltec_wifi_lora_32_v3
framework = arduino

monitor_speed = 115200
upload_speed = 115200
upload_port = COM3
monitor_port = COM3

lib_ldf_mode = deep+

lib_deps = 
	heltecautomation/Heltec ESP32 Dev-Boards@^2.1.5
	adafruit/Adafruit BMP085 Library@^1.2.4
	sensirion/Sensirion Core@^0.7.3
	sensirion/Sensirion I2C SCD4x@^1.1.0

build_flags = 
	-DHELTEC_BOARD=30
	-DHELTEC_WIFI_LORA_32_V3
	-DWIFI_LORA_32_V3
	-DMCU_ESP32_S3
	-DRADIO_CHIP_SX1262
	-DSLOW_CLK_TPYE=0
	-DREGION_US915
	-DACTIVE_REGION=LORAMAC_REGION_US915
	-DLoRaWAN_DEBUG_LEVEL=0
	-DGPIO_PIN_COUNT=SOC_GPIO_PIN_COUNT
	-Wno-narrowing
	-Wno-overflow