[env:heltec_wifi_lora_32_v3]
platform = espressif32@6.8.1
board = heltec_wifi_lora_32_v3
framework = arduino

monitor_speed = 115200
upload_port = COM3
monitor_port = COM3

lib_ldf_mode = deep+

lib_deps =
    heltecautomation/Heltec ESP32 Dev-Boards @ ^2.1.5
    adafruit/Adafruit BMP085 Library
    sensirion/Sensirion I2C SCD4x

build_flags =
    -D HELTEC_BOARD=30
    -D HELTEC_WIFI_LORA_32_V3
    -D WIFI_LORA_32_V3
    -D MCU_ESP32_S3
    -D RADIO_CHIP_SX1262
    -D SLOW_CLK_TPYE=0
    -D REGION_US915
    -D ACTIVE_REGION=LORAMAC_REGION_US915
    -D LoRaWAN_DEBUG_LEVEL=0
    -D GPIO_PIN_COUNT=SOC_GPIO_PIN_COUNT